# docker-compose.yaml
version: '3.8'

services:
  postgres_db:
    image: postgres:16-alpine
    container_name: backend_axum_template_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: supersecretpassword
      POSTGRES_DB: app_development
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: "no"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d app_development"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
